"""Добавление created_at в таблицу Roadmap

Revision ID: 1c9a661d62b2
Revises: 
Create Date: 2025-04-08 20:28:32.120048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c9a661d62b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Category_category_id'), 'Category', ['category_id'], unique=False)
    op.alter_column('Comment', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_Comment_comment_id'), 'Comment', ['comment_id'], unique=False)
    op.add_column('Like', sa.Column('created_at', sa.TIMESTAMP(), nullable=False))
    op.create_index(op.f('ix_Like_like_id'), 'Like', ['like_id'], unique=False)
    op.create_unique_constraint('unique_like', 'Like', ['user_id', 'roadmap_id'])
    op.add_column('Roadmap', sa.Column('created_at', sa.TIMESTAMP(), nullable=False))
    op.create_index(op.f('ix_Roadmap_roadmap_id'), 'Roadmap', ['roadmap_id'], unique=False)
    op.add_column('Step', sa.Column('created_at', sa.TIMESTAMP(), nullable=False))
    op.create_index(op.f('ix_Step_step_id'), 'Step', ['step_id'], unique=False)
    op.execute('ALTER TABLE "User" ALTER COLUMN role TYPE INTEGER USING role::INTEGER')
    op.create_index(op.f('ix_User_user_id'), 'User', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_user_id'), table_name='User')
    op.alter_column('User', 'role',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=45),
               existing_nullable=False)
    op.drop_index(op.f('ix_Step_step_id'), table_name='Step')
    op.drop_column('Step', 'created_at')
    op.drop_index(op.f('ix_Roadmap_roadmap_id'), table_name='Roadmap')
    op.drop_column('Roadmap', 'created_at')
    op.drop_constraint('unique_like', 'Like', type_='unique')
    op.drop_index(op.f('ix_Like_like_id'), table_name='Like')
    op.drop_column('Like', 'created_at')
    op.drop_index(op.f('ix_Comment_comment_id'), table_name='Comment')
    op.alter_column('Comment', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_Category_category_id'), table_name='Category')
    # ### end Alembic commands ###
