"""Initial migration

Revision ID: c4c8d49da499
Revises: 
Create Date: 2025-04-07 22:41:55.605682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4c8d49da499'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index(op.f('ix_Category_category_id'), 'Category', ['category_id'], unique=False)
    op.create_table('User',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', postgresql.BYTEA(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_User_user_id'), 'User', ['user_id'], unique=False)
    op.create_table('Roadmap',
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['Category.category_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('roadmap_id')
    )
    op.create_index(op.f('ix_Roadmap_roadmap_id'), 'Roadmap', ['roadmap_id'], unique=False)
    op.create_table('Comment',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('roadmap_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['Roadmap.roadmap_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_index(op.f('ix_Comment_comment_id'), 'Comment', ['comment_id'], unique=False)
    op.create_table('Like',
    sa.Column('like_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('roadmap_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['Roadmap.roadmap_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('like_id'),
    sa.UniqueConstraint('user_id', 'roadmap_id', name='unique_like')
    )
    op.create_index(op.f('ix_Like_like_id'), 'Like', ['like_id'], unique=False)
    op.create_table('Step',
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=True),
    sa.Column('step_title', sa.String(length=255), nullable=False),
    sa.Column('step_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['Roadmap.roadmap_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('step_id')
    )
    op.create_index(op.f('ix_Step_step_id'), 'Step', ['step_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Step_step_id'), table_name='Step')
    op.drop_table('Step')
    op.drop_index(op.f('ix_Like_like_id'), table_name='Like')
    op.drop_table('Like')
    op.drop_index(op.f('ix_Comment_comment_id'), table_name='Comment')
    op.drop_table('Comment')
    op.drop_index(op.f('ix_Roadmap_roadmap_id'), table_name='Roadmap')
    op.drop_table('Roadmap')
    op.drop_index(op.f('ix_User_user_id'), table_name='User')
    op.drop_table('User')
    op.drop_index(op.f('ix_Category_category_id'), table_name='Category')
    op.drop_table('Category')
    # ### end Alembic commands ###
